// 번역할 언어 데이터 정의
const messages = { 
    ko: { // 한국어
      profile: '프로필',
      name: '이름',
      email: '이메일',
      maxBudget: '최대 예산',
      notification: '알림',
      language: '언어',
      theme: '테마',
      edit: '수정',
      mainPage: '메인 페이지로',
      warning: '경고',
      enterNameEmail: '이름과 이메일을 입력하세요.',
      close: '닫기',
      addTransaction: '거래 내역 추가',
      date: '날짜',
      category: '카테고리',
      food: '식비',
      transportation: '교통비',
      communication: '통신비',
      etc: '기타',
      income: '수입',
      netProfit: '순수익',
      expense: '지출',
      history: '거래 내역',
      enterTransaction: '거래 내역을 입력하세요.',
      enterAmount: '금액을 입력하세요.',
      enterMemo: '메모를 입력하세요.',
      enterName: '이름을 입력하세요.',
      enterEmail: '이메일을 입력하세요.',
      enterMaxBudget: '최대 예산을 입력하세요.',
      amount: '금액',
      memo: '메모',
      registration: '등록',
      edit: '수정',
      cancel: '취소',
      delete: '삭제',
      won: '원',
      month: '월',
      listTransaction: '+ 거래 내역 목록',
      previous: '이전',
      next: '다음',
      summaryTransaction: '거래 내역 요약',
      dateTransaction: '거래 날짜',
      error: '잘못된 주소입니다.',
      monthlyExpense: '월별 지출',
    
    },
    en: { // 영어
      profile: 'Profile',
      name: 'Name',
      email: 'Email',
      maxBudget: 'Max Budget',
      notification: 'Noti',
      language: 'Lang',
      theme: 'Theme',
      edit: 'Edit',
      mainPage: 'Go to Main Page',
      warning: 'Warning',
      enterNameEmail: 'Please enter name and email.',
      close: 'Close',
      addTransaction: 'Add Transaction',
      date: 'Date',
      category: 'Category',
      food: 'Food Cost',
      transportation: 'Transportation Cost',
      communication: 'Communication Cost',
      etc: 'Etc',
      income: 'Income',
      netProfit: 'Net Profit',
      expense: 'Expense',
      history: 'Transaction History',
      enterTransaction: 'Please enter transaction details.',
      enterAmount: 'Please enter amount.',
      enterMemo: 'Please enter memo.',
      enterName: 'Please enter name.',
      enterEmail: 'Please enter email.',
      enterMaxBudget: 'Please enter max budget.',
      amount: 'Amount',
      memo: 'Memo',
      registration: 'Regis',
      edit: 'Edit',
      cancel: 'Cancel',
      delete: 'Delete',
      won: '￦',
      month: 'mth',
      listTransaction: '+ List of Transactions',
      previous: 'Prev',
      next: 'Next',
      summaryTransaction: 'Summary of Transactions',
      dateTransaction: 'Transaction Date',
      error: '404',
      monthlyExpense: 'Monthly Expense',
    },
  };
  
  export default messages;
  
